apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfssb-daemon
spec:
  selector:
    matchLabels:
      app: hdfssb-daemon # has to match .spec.template.metadata.labels
  serviceName: "hdfssb-daemon"
  replicas: 1
  template:
    metadata:
      labels:
        app: hdfssb-daemon # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: reciver
          image: damenus/hdfssb-processor:0.3
#          imagePullPolicy: Always
          ports:
            - containerPort: 60000
              name: "tcp-connection"
          volumeMounts:
            - name: host-path
              mountPath: /daemon/daemon_dir
          env:
            - name: OWN_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: ["/bin/bash"]
          args: ["-c","sleep 3600"]
        - name: sender
          image: damenus/hdfssb-processor:0.3
#          imagePullPolicy: Always
          ports:
            - containerPort: 60002
              name: "tcp-connection"
          volumeMounts:
            - name: host-path
              mountPath: /daemon/daemon_dir
          env:
            - name: OWN_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: ["/bin/bash"]
          args: ["-c","sleep 3600"]
          #  export PYTHONPATH=.. ; python3 hdfssb/daemon/main2.py
      volumes:
        - name: host-path
          hostPath:
            path: /daemon/daemon_dir
#    - name:  example-local-pv
#      persistentVolumeClaim:
#       claimName:  example-local-pv

---
apiVersion: v1
kind: Service
metadata:
  name: hdfssb-daemon
  labels:
    run: hdfssb-daemon
spec:
  clusterIP: None
  ports:
  - name: reciver-port
    port: 60000
    protocol: TCP
  - name: sender-port
    port: 60002
    protocol: TCP
  selector:
    run: hdfssb-daemon
